apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik            # 必须叫 traefik，对应 k3s 内置的那个 chart
  namespace: kube-system   # 必须在 kube-system
spec:
  valuesContent: |-
    service:
      spec:
        externalTrafficPolicy: Local
